// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBIjk4Me0Li3zbPAZGJK3XbkamJxVt0o',
    appId: '1:261551346702:web:3474d8d82c59bfc6bad85f',
    messagingSenderId: '261551346702',
    projectId: 'abhaya-759a7',
    authDomain: 'abhaya-759a7.firebaseapp.com',
    storageBucket: 'abhaya-759a7.firebasestorage.app',
    measurementId: 'G-3FCMFSCVNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAlx0Usl0VNQoF3On2hP_SFpm59Ih05BA',
    appId: '1:261551346702:android:7734eb8b53adb12dbad85f',
    messagingSenderId: '261551346702',
    projectId: 'abhaya-759a7',
    storageBucket: 'abhaya-759a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6iSBIMy1whSXOrsV8mC2vemPhDVh_hRY',
    appId: '1:261551346702:ios:0ac089f0009524ffbad85f',
    messagingSenderId: '261551346702',
    projectId: 'abhaya-759a7',
    storageBucket: 'abhaya-759a7.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6iSBIMy1whSXOrsV8mC2vemPhDVh_hRY',
    appId: '1:261551346702:ios:0ac089f0009524ffbad85f',
    messagingSenderId: '261551346702',
    projectId: 'abhaya-759a7',
    storageBucket: 'abhaya-759a7.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBIjk4Me0Li3zbPAZGJK3XbkamJxVt0o',
    appId: '1:261551346702:web:2408051b198115d4bad85f',
    messagingSenderId: '261551346702',
    projectId: 'abhaya-759a7',
    authDomain: 'abhaya-759a7.firebaseapp.com',
    storageBucket: 'abhaya-759a7.firebasestorage.app',
    measurementId: 'G-MMPCZ2RRH6',
  );
}
