import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart';

// Import your screen files - ensure these paths match your folder structure
import 'screens/launch_screen.dart';
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/languageselection_screen.dart';
import 'screens/home_screen.dart';
import 'services/auth_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with the options generated by the FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const AbhayaApp());
}

class AbhayaApp extends StatelessWidget {
  const AbhayaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Providing AuthService to the widget tree if needed for session management
        Provider<AuthService>(create: (_) => AuthService()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'ABHAYA',
        theme: ThemeData(
          // Using the Abhaya theme colors
          primaryColor: const Color(0xFFD32F2F),
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFFD32F2F),
            primary: const Color(0xFFD32F2F),
          ),
          // Global background color matching the prototype video
          scaffoldBackgroundColor: const Color(0xFFFDE8E8),
          useMaterial3: true,
        ),
        
        // The App starts at the Launch Screen
        home: const LaunchScreen(),
        
        // Named routes for easier navigation throughout the app
        routes: {
          '/login': (context) => const LoginScreen(),
          '/signup': (context) => const SignupScreen(),
          '/language': (context) => const LanguageSelectionScreen(),
          '/home': (context) => const HomeScreen(),
        },
      ),
    );
  }
}


